### ISSUE TITLE
Any way to modify the tree properties

### ISSUE THREAD

**Issue by russell-islam** [rs-embedded/fdt-rs#9]
I wanted to load the tree and modify that in memory, and eventually flash that to the file again. Is this supported?

**Comment by spwilson2** [comment]
Hi @russell-islam, Unfortunately that’s not a supported use case. This tool simply acts as a read-only method for traversing an existing FDT.

On their own FDTs are not well-suited for in-place edits. (Adding properties/nodes would effectively be like pushing elements in an array.)

Another tool could leverage this one to build a more write-efficient data structure which eventually serializes back into an FDT, but this tool does not support that.

**Comment by russell-islam** [comment]
> Hi @russell-islam, Unfortunately that’s not a supported use case. This tool simply acts as a read-only method for traversing an existing FDT.
> 
> On their own FDTs are not well-suited for in-place edits. (Adding properties/nodes would effectively be like pushing elements in an array.)
> 
> Another tool could leverage this one to build a more write-efficient data structure which eventually serializes back into an FDT, but this tool does not support that.

Thanks for the reply. Do you know any such tool written in rust?

**Comment by spwilson2** [comment]
I don’t see one with a quick search. You might be able to combine this crate and vm-fdt to get what you want. Though I’m not familiar enough with the crate to say how well it works.

(Just iterate through the tree using this crate to create the vm-fdt model, and then edit the nodes using that model.)

**Comment by russell-islam** [comment]
Thank you.
